name: Simple Python Action

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run Python Script
      run: python ./hello.py
      working-directory: ./  # Set the working directory to the root of the repository
